### ISSUE TITLE
【发布计划】0.1.0 版本

### ISSUE THREAD

**Issue by Hentioe** [Hentioe/mikack-mobile#95]
- [x] 解决剩余的一些必要 issue（依赖本 issue 的版本更新实现）
- [x] 空内容的快捷导航提示
   - [x] 书架为空时，去「仓库看看」或「全局搜索」找找
- [x] 实现基于 Github Release 的版本更新
   - [x] 调用 API 检测新版本
   - [x] 读取更新日志
   - [x] 获取对应的 assets 链接
- [x] 丰富使用条款内容
- [x] 丰富 README.md 内容
- [x] 生成 apk 密钥，用密钥打包应用
